### ISSUE TITLE
Expect .gitignore

### ISSUE THREAD

**Issue by ShamrockLee** [fan84sunny/PTGAN#1]
People usually use the file `.gitignore` to exclude some files (e.g. the `__pycache__` directory) from the source tree.

Templates can be found inside https://github.com/github/gitignore . I would recommend https://github.com/github/gitignore/blob/main/Python.gitignore for Python projects and https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore as you seem to use the JetBrains IDE. Just copy the lines needed from those files, paste them into the file `.gitignore`, and put it on the root of this project.

Reference:
*   Scott Chacon and Ben Straub. Pro Git. https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#_ignoring
*    GitHub. GitHub Docs. https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files

**Comment by fan84sunny** [comment]
Thank you for your kind recommendation.
