### ISSUE TITLE
Expect LICENSE to allow legitimate forking

### ISSUE THREAD

**Issue by ShamrockLee** [fan84sunny/PTGAN#2]
DISCLAIMER: I'm not a lawyer. The following should not be considered a legal advice.

When developers fork this project, they essentially create a clone and distribute it publicly. When they modify the content of the forked repository online, they essentially distribute their derived work based on this project.

Without a license, these actions would be considered copyright violations by the holder(s), and the devolopers who fork this repo would be at risk of legal consequence.

The GitHub Terms of Use gives every user the right to "view and fork" every public repository.[1][2] However, it's pointless for a user to "just fork" a repo without the right to modify it.

The LICENSE file was removed in ade674665a74561fa2ed1f1d76ff15cd5d84b857 . A license that permits the

*   execution,
*   redistribution of this work, and
*   redistribution of the derived work

is nessesary.

Citation:

1: GitHub. Licensing a repository. GitHub Doc. https://opensource.stackexchange.com/questions/1154/how-does-githubs-forking-right-cope-with-an-all-rights-reserved-project

2: SO contributors. How does GitHub's "forking right" cope with an "All rights reserved" project?. Open Source Stack Exchange. https://opensource.stackexchange.com/questions/1154/how-does-githubs-forking-right-cope-with-an-all-rights-reserved-project

**Comment by fan84sunny** [comment]
Thank you. We still improve this code.
